// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	_ "embed"
	"github.com/swaggo/swag"

)

//go:embed swagger.yaml
var Spec []byte


// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	// Host:             "petstore.swagger.io",
	BasePath:         "/swagger",
	Schemes:          []string{},
	Title:            "Travel Warrant REST api",
	Description:      "This is v1 api for travel warrant..",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  string(Spec),
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
